server:
  port: 8080
spring:
  application:
    name: My-OpenAI
  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
    suffix: .html
    servlet:
      content-type: text/html
open:
  ai:
    api:
      completions: https://api.openai.com/v1/completions
      images: https://api.openai.com/v1/images/generations
    apiKey: YOUR_API_KEY
    organization: YOUR_ORGANIZATION
